name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      env:
        NODE_ENV: production
        
    # デプロイ先に応じて以下を変更
    # 例: AWS、Heroku、Azure など
    - name: Deploy to production
      run: |
        # デプロイスクリプト
        echo "Deploying to production server"
      env:
        # 本番環境の認証情報
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} 